---
default_options:
  region: us-east-1

aws_accounts:
  - account_id: "123456789012"
    name: someaccount
    description: Some AWS Account
    is_prod: true

default_account:
  name: someaccount
  # role: Admin

sso:
  url: "https://sso.example.com/"
  auth_method: kerberos
  ca_file: "$CONFIG_ROOT/ca-bundle.crt"
